version: "3.8"

services:
  app:
    image: ${IMAGE}:latest
    container_name: ${IMAGE}
    restart: always
    env_file: .env
    depends_on:
      - mongo
      - postgres
    ports:
      - "${PORT}:${PORT}"

  mongo:
    build: ./mongo
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  postgres:
    build: ./postgres
    container_name: postgres
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  pg_data:
