name: Create.GitHub.Tag

on:
  workflow_call:
    inputs:
      major:
        required: true
        type: string
      minor:
        required: true
        type: string
      patch:
        required: true
        type: string

jobs:
  create-tags:
    name: Create.GitHub.Tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and push version tags
        env:
          MAJOR: ${{ inputs.major }}
          MINOR: ${{ inputs.minor }}
          PATCH: ${{ inputs.patch }}
        run: |
          set -e
          VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "🏷️ Creating tag ${VERSION}"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch --tags

          git tag -f "${VERSION}"
          git push origin "${VERSION}" --force

          echo "✅ Tag created: ${VERSION}"
