name: Setup.NGINX.Proxy

on:
  workflow_call:
    secrets:
      SERVER_SSH_KEY:
        required: true
      SERVER_HOST:
        required: true
      SERVER_USER:
        required: true
      DOMAIN_NAME:
        required: true
      SERVER_APP_DIR:
        required: true
      SERVER_SSH_PORT:
        required: true
      SERVER_PASSWORD:
        required: true
      SSH_PORT:
        required: true
      MONGO_PORT:
        required: true
      POSTGRES_PORT:
        required: true

jobs:
  setup-database-nginx:
    name: Configure Database Reverse Proxy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Configure Nginx Reverse Proxy for Databases
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          MONGO_PORT: ${{ secrets.MONGO_PORT }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        run: |
          echo "⚙️ Setting up Nginx proxy for MongoDB and PostgreSQL..."

          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} bash -s -- "$SERVER_PASSWORD" "$DOMAIN_NAME" "$MONGO_PORT" "$POSTGRES_PORT" <<'EOF'
          set -e
          SERVER_PASSWORD="$1"
          DOMAIN="$2"
          MONGO_PORT="$3"
          POSTGRES_PORT="$4"

          NGINX_CONF="/etc/nginx/streams-enabled/${DOMAIN}.conf"

          echo "🔍 Checking Nginx installation..."
          if ! command -v nginx &>/dev/null; then
            echo "📦 Installing Nginx..."
            echo "$SERVER_PASSWORD" | sudo -S apt update -y
            echo "$SERVER_PASSWORD" | sudo -S apt install nginx -y
            echo "$SERVER_PASSWORD" | sudo -S systemctl enable nginx
            echo "$SERVER_PASSWORD" | sudo -S systemctl start nginx
          fi
          echo "✅ Nginx ready."

          echo "🔍 Checking Certbot installation..."
          if ! command -v certbot &>/dev/null; then
            echo "📦 Installing Certbot..."
            echo "$SERVER_PASSWORD" | sudo -S apt install -y certbot python3-certbot-nginx python3-certbot
          fi
          echo "✅ Certbot ready."

          # -----------------------------------------------------
          # 1. HTTP config for Certbot validation (no SSL yet)
          # -----------------------------------------------------
          echo "🧱 Creating temporary HTTP-only config for \$DOMAIN ..."
          cat <<CONFIG > temp.conf
          # Stream TCP proxy for PostgreSQL & MongoDB no SSL

          # --- PostgreSQL Proxy ---
          upstream postgres_backend {
              server 127.0.0.1:5432;  # original PostgreSQL port
          }

          server {
              listen 15432;

              # Proxy TCP
              proxy_pass postgres_backend;

              # Timeout
              proxy_timeout 10m;
              proxy_connect_timeout 10s;
          }

          # --- MongoDB Proxy ---
          upstream mongo_backend {
              server 127.0.0.1:27017;  # original MongoDB port
          }

          server {
              listen 27018;

              # Proxy TCP
              proxy_pass mongo_backend;

              # Timeout
              proxy_timeout 10m;
              proxy_connect_timeout 10s;
          }
          CONFIG

          echo "$SERVER_PASSWORD" | sudo -S mv temp.conf "$NGINX_CONF"

          echo "$SERVER_PASSWORD" | sudo -S nginx -t
          echo "$SERVER_PASSWORD" | sudo -S systemctl reload nginx
          echo "✅ HTTP config loaded."

          # -----------------------------------------------------
          # 2. Issue SSL certificate (standalone mode)
          # -----------------------------------------------------
          echo "🔍 Checking SSL certificate for \$DOMAIN..."
          CERT_PATH="/etc/letsencrypt/live/${DOMAIN}"
          if [ -f "$CERT_PATH/fullchain.pem" ]; then
            echo "✅ SSL certificate already exists at $CERT_PATH"
          else
            echo "📜 Requesting new SSL certificate (standalone mode)..."
            echo "$SERVER_PASSWORD" | sudo -S systemctl stop nginx
            if ! echo "$SERVER_PASSWORD" | sudo -S certbot certonly --standalone \
              -d "$DOMAIN" --non-interactive --agree-tos -m roberthost.vn@gmail.com; then
              echo "❌ Failed to issue SSL certificate. Check DNS and port 80 access."
              echo "$SERVER_PASSWORD" | sudo -S systemctl start nginx
              exit 1
            fi
            echo "$SERVER_PASSWORD" | sudo -S systemctl start nginx
            echo "✅ SSL certificate successfully issued for \$DOMAIN"
          fi

          # -----------------------------------------------------
          # 3. Verify certificate existence
          # -----------------------------------------------------
          if [ ! -f "$CERT_PATH/fullchain.pem" ]; then
            echo "⚠️ Certificate for $DOMAIN not found in $CERT_PATH"
            echo "🔍 Searching for existing certificates..."

            # Run find below sudo permission, password to stdin right way
            ALT_CERT=$(echo "$SERVER_PASSWORD" | sudo -S bash -c "find /etc/letsencrypt/live -maxdepth 1 -type d ! -path '/etc/letsencrypt/live' | head -n 1")

            if [ -n "$ALT_CERT" ] && echo "$SERVER_PASSWORD" | sudo -S test -f "$ALT_CERT/fullchain.pem"; then
              echo "✅ Using existing certificate from $ALT_CERT"
              CERT_PATH="$ALT_CERT"
            else
              echo "❌ No valid certificate found. Aborting."
              exit 1
            fi
          fi

          # -----------------------------------------------------
          # 4. Replace config with SSL-enabled TCP reverse proxy
          # -----------------------------------------------------
          echo "🧱 Creating final HTTPS config for MongoDB and PostgreSQL..."
          cat <<CONFIG > temp.conf
          # Stream TCP proxy for PostgreSQL & MongoDB with SSL

          # --- PostgreSQL Proxy ---
          upstream postgres_backend {
              server 127.0.0.1:5432;  # original PostgreSQL port
          }

          server {
              listen 15432; # Using TLS passthrough inside psql
              # listen 15432 ssl;

              # Proxy TCP
              proxy_pass postgres_backend;

              # SSL
              ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;

              # Timeout
              proxy_timeout 10m;
              proxy_connect_timeout 10s;

              # SSL options safety
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_ciphers HIGH:!aNULL:!MD5;
          }

          # --- MongoDB Proxy ---
          upstream mongo_backend {
              server 127.0.0.1:27017;  # original MongoDB port
          }

          server {
              listen 27018; # Using TLS passthrough inside mongod
              # listen 27018 ssl;

              # Proxy TCP
              proxy_pass mongo_backend;

              # SSL
              ssl_certificate     ${CERT_PATH}/fullchain.pem;
              ssl_certificate_key ${CERT_PATH}/privkey.pem;

              # Timeout
              proxy_timeout 10m;
              proxy_connect_timeout 10s;

              # SSL options safety
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_ciphers HIGH:!aNULL:!MD5;
          }

          CONFIG

          echo "$SERVER_PASSWORD" | sudo -S mv temp.conf "$NGINX_CONF"

          echo "🔍 Testing Nginx config..."

          echo "$SERVER_PASSWORD" | sudo -S nginx -t
          echo "$SERVER_PASSWORD" | sudo -S systemctl reload nginx

          echo "✅ Database reverse proxy configured successfully for $DOMAIN"
          echo "🌐 Mongo: https://$DOMAIN/mongo/"
          echo "🌐 Postgres: https://$DOMAIN/postgres/"
          EOF

      - name: Verify Nginx
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          echo "🔎 Checking Nginx service status..."
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} bash -s -- "$SERVER_PASSWORD" << 'EOF'
            set -e
            SERVER_PASSWORD="$1"
            if ! echo "$SERVER_PASSWORD" | sudo -S systemctl is-active --quiet nginx; then
              echo "❌ Nginx service not active!"
              exit 1
            fi
            echo "✅ Nginx service is active and running."
          EOF
